/**
 * Hadith of the day — a small curated set of widely known, authentic (sahih)
 * narrations, mostly from an-Nawawi's Forty and Riyad as-Salihin, with the
 * primary reference shown in the UI. Arabic is the standard matn; translations
 * are close renderings for reading at a desk, not scholarly editions.
 * If you add entries: only graded-sahih narrations with a book + number.
 */
export default [
  { ar: 'إِنَّمَا الأَعْمَالُ بِالنِّيَّاتِ، وَإِنَّمَا لِكُلِّ امْرِئٍ مَا نَوَى', en: 'Actions are judged by intentions, and every person will have what they intended.', fr: 'Les actes ne valent que par les intentions, et chacun n’aura que ce qu’il a eu l’intention de faire.', ref: 'Bukhari 1, Muslim 1907 · Nawawi 1' },
  { ar: 'الدِّينُ النَّصِيحَةُ', en: 'The religion is sincere counsel.', fr: 'La religion, c’est le conseil sincère.', ref: 'Muslim 55 · Nawawi 7' },
  { ar: 'مَا نَهَيْتُكُمْ عَنْهُ فَاجْتَنِبُوهُ، وَمَا أَمَرْتُكُمْ بِهِ فَأْتُوا مِنْهُ مَا اسْتَطَعْتُمْ', en: 'What I have forbidden you, avoid; what I have commanded you, do as much of it as you can.', fr: 'Ce que je vous ai interdit, évitez-le ; ce que je vous ai ordonné, faites-en ce que vous pouvez.', ref: 'Bukhari 7288, Muslim 1337 · Nawawi 9' },
  { ar: 'مِنْ حُسْنِ إِسْلَامِ الْمَرْءِ تَرْكُهُ مَا لَا يَعْنِيهِ', en: 'Part of the excellence of a person’s Islam is leaving what does not concern them.', fr: 'Fait partie de la beauté de l’islam d’une personne le fait de délaisser ce qui ne la regarde pas.', ref: 'Tirmidhi 2317 · Nawawi 12' },
  { ar: 'لَا يُؤْمِنُ أَحَدُكُمْ حَتَّى يُحِبَّ لِأَخِيهِ مَا يُحِبُّ لِنَفْسِهِ', en: 'None of you truly believes until he loves for his brother what he loves for himself.', fr: 'Aucun de vous ne croit vraiment tant qu’il n’aime pas pour son frère ce qu’il aime pour lui-même.', ref: 'Bukhari 13, Muslim 45 · Nawawi 13' },
  { ar: 'لَا تَغْضَبْ', en: 'A man asked the Prophet ﷺ for advice. He said: “Do not get angry,” and repeated it several times.', fr: 'Un homme demanda conseil au Prophète ﷺ. Il dit : « Ne te mets pas en colère », et le répéta plusieurs fois.', ref: 'Bukhari 6116 · Nawawi 16' },
  { ar: 'إِنَّ اللَّهَ كَتَبَ الإِحْسَانَ عَلَى كُلِّ شَيْءٍ', en: 'Allah has prescribed excellence (ihsan) in everything.', fr: 'Allah a prescrit l’excellence en toute chose.', ref: 'Muslim 1955 · Nawawi 17' },
  { ar: 'اتَّقِ اللَّهَ حَيْثُمَا كُنْتَ، وَأَتْبِعِ السَّيِّئَةَ الْحَسَنَةَ تَمْحُهَا، وَخَالِقِ النَّاسَ بِخُلُقٍ حَسَنٍ', en: 'Be mindful of Allah wherever you are; follow a bad deed with a good one and it will erase it; and treat people with good character.', fr: 'Crains Allah où que tu sois ; fais suivre la mauvaise action d’une bonne qui l’effacera ; et comporte-toi avec les gens avec un bon caractère.', ref: 'Tirmidhi 1987 · Nawawi 18' },
  { ar: 'احْفَظِ اللَّهَ يَحْفَظْكَ، احْفَظِ اللَّهَ تَجِدْهُ تُجَاهَكَ … وَاعْلَمْ أَنَّ مَا أَخْطَأَكَ لَمْ يَكُنْ لِيُصِيبَكَ، وَمَا أَصَابَكَ لَمْ يَكُنْ لِيُخْطِئَكَ', en: 'Be mindful of Allah and He will protect you… Know that what missed you was never going to reach you, and what reached you was never going to miss you.', fr: 'Préserve Allah, Il te préservera… Sache que ce qui t’a manqué n’allait pas t’atteindre, et que ce qui t’a atteint n’allait pas te manquer.', ref: 'Tirmidhi 2516 · Nawawi 19' },
  { ar: 'إِذَا لَمْ تَسْتَحِ فَاصْنَعْ مَا شِئْتَ', en: 'If you feel no shame, then do as you wish.', fr: 'Si tu n’as pas de pudeur, fais ce que tu veux.', ref: 'Bukhari 3484 · Nawawi 20' },
  { ar: 'قُلْ: آمَنْتُ بِاللَّهِ، ثُمَّ اسْتَقِمْ', en: 'Say: “I believe in Allah,” then be steadfast.', fr: 'Dis : « Je crois en Allah », puis reste droit.', ref: 'Muslim 38 · Nawawi 21' },
  { ar: 'الطُّهُورُ شَطْرُ الإِيمَانِ، وَالْحَمْدُ لِلَّهِ تَمْلَأُ الْمِيزَانَ', en: 'Purity is half of faith, and “alhamdulillah” fills the scale.', fr: 'La pureté est la moitié de la foi, et « al-hamdu lillah » remplit la balance.', ref: 'Muslim 223 · Nawawi 23' },
  { ar: 'لَا ضَرَرَ وَلَا ضِرَارَ', en: 'There should be neither harm nor reciprocating harm.', fr: 'Pas de préjudice, ni de préjudice en retour.', ref: 'Ibn Majah 2341 · Nawawi 32' },
  { ar: 'مَنْ نَفَّسَ عَنْ مُؤْمِنٍ كُرْبَةً مِنْ كُرَبِ الدُّنْيَا نَفَّسَ اللَّهُ عَنْهُ كُرْبَةً مِنْ كُرَبِ يَوْمِ الْقِيَامَةِ … وَاللَّهُ فِي عَوْنِ الْعَبْدِ مَا كَانَ الْعَبْدُ فِي عَوْنِ أَخِيهِ', en: 'Whoever relieves a believer of a hardship in this world, Allah will relieve him of a hardship on the Day of Resurrection… Allah helps the servant as long as the servant helps his brother.', fr: 'Quiconque soulage un croyant d’une peine de ce monde, Allah le soulagera d’une peine du Jour de la Résurrection… Allah aide le serviteur tant que le serviteur aide son frère.', ref: 'Muslim 2699 · Nawawi 36' },
  { ar: 'كُنْ فِي الدُّنْيَا كَأَنَّكَ غَرِيبٌ أَوْ عَابِرُ سَبِيلٍ', en: 'Be in this world as if you were a stranger or a traveller passing through.', fr: 'Sois en ce monde comme un étranger ou un voyageur de passage.', ref: 'Bukhari 6416 · Nawawi 40' },
  { ar: 'الْمُؤْمِنُ الْقَوِيُّ خَيْرٌ وَأَحَبُّ إِلَى اللَّهِ مِنَ الْمُؤْمِنِ الضَّعِيفِ، وَفِي كُلٍّ خَيْرٌ. احْرِصْ عَلَى مَا يَنْفَعُكَ، وَاسْتَعِنْ بِاللَّهِ وَلَا تَعْجَزْ', en: 'The strong believer is better and more beloved to Allah than the weak believer, though there is good in both. Strive for what benefits you, seek Allah’s help, and do not give up.', fr: 'Le croyant fort est meilleur et plus aimé d’Allah que le croyant faible, et il y a du bien en chacun. Recherche ce qui t’est utile, demande l’aide d’Allah et ne baisse pas les bras.', ref: 'Muslim 2664' },
  { ar: 'لَوْ أَنَّكُمْ تَوَكَّلْتُمْ عَلَى اللَّهِ حَقَّ تَوَكُّلِهِ لَرَزَقَكُمْ كَمَا يَرْزُقُ الطَّيْرَ، تَغْدُو خِمَاصًا وَتَرُوحُ بِطَانًا', en: 'If you relied on Allah as He should be relied upon, He would provide for you as He provides for the birds: they go out hungry in the morning and return full in the evening.', fr: 'Si vous vous en remettiez à Allah comme il se doit, Il vous pourvoirait comme Il pourvoit aux oiseaux : ils partent le ventre vide le matin et reviennent rassasiés le soir.', ref: 'Tirmidhi 2344 (sahih)' },
  { ar: 'عَجَبًا لِأَمْرِ الْمُؤْمِنِ، إِنَّ أَمْرَهُ كُلَّهُ خَيْرٌ … إِنْ أَصَابَتْهُ سَرَّاءُ شَكَرَ فَكَانَ خَيْرًا لَهُ، وَإِنْ أَصَابَتْهُ ضَرَّاءُ صَبَرَ فَكَانَ خَيْرًا لَهُ', en: 'How wonderful is the affair of the believer — all of it is good: if ease comes to him he is grateful, and that is good for him; if hardship comes he is patient, and that is good for him.', fr: 'Comme l’affaire du croyant est étonnante : tout lui est bien. Si l’aisance lui vient, il remercie et c’est un bien ; si l’épreuve lui vient, il patiente et c’est un bien.', ref: 'Muslim 2999' },
  { ar: 'كَلِمَتَانِ خَفِيفَتَانِ عَلَى اللِّسَانِ، ثَقِيلَتَانِ فِي الْمِيزَانِ، حَبِيبَتَانِ إِلَى الرَّحْمَنِ: سُبْحَانَ اللَّهِ وَبِحَمْدِهِ، سُبْحَانَ اللَّهِ الْعَظِيمِ', en: 'Two phrases light on the tongue, heavy on the scale, beloved to the Most Merciful: Subhan Allahi wa bihamdihi, Subhan Allahil-‘Azim.', fr: 'Deux paroles légères sur la langue, lourdes dans la balance, aimées du Tout-Miséricordieux : Subhan Allahi wa bihamdihi, Subhan Allahil-‘Azim.', ref: 'Bukhari 6406, Muslim 2694' },
  { ar: 'مَنْ صَلَّى عَلَيَّ صَلَاةً صَلَّى اللَّهُ عَلَيْهِ بِهَا عَشْرًا', en: 'Whoever sends one salah (blessing) upon me, Allah sends ten upon him.', fr: 'Quiconque prie une fois sur moi, Allah prie dix fois sur lui.', ref: 'Muslim 408' },
  { ar: 'إِنَّ أَحَبَّ الأَعْمَالِ إِلَى اللَّهِ أَدْوَمُهَا وَإِنْ قَلَّ', en: 'The most beloved deeds to Allah are the most consistent, even if small.', fr: 'Les œuvres les plus aimées d’Allah sont les plus régulières, même si elles sont petites.', ref: 'Bukhari 6464, Muslim 783' },
  { ar: 'نِعْمَتَانِ مَغْبُونٌ فِيهِمَا كَثِيرٌ مِنَ النَّاسِ: الصِّحَّةُ وَالْفَرَاغُ', en: 'Two blessings many people are cheated of: health and free time.', fr: 'Deux bienfaits dont beaucoup de gens sont lésés : la santé et le temps libre.', ref: 'Bukhari 6412' },
  { ar: 'إِنَّ لِبَدَنِكَ عَلَيْكَ حَقًّا، وَإِنَّ لِعَيْنِكَ عَلَيْكَ حَقًّا', en: 'Your body has a right over you, and your eyes have a right over you.', fr: 'Ton corps a un droit sur toi, et tes yeux ont un droit sur toi.', ref: 'Bukhari 1975' },
  { ar: 'مَنْ سَلَكَ طَرِيقًا يَلْتَمِسُ فِيهِ عِلْمًا سَهَّلَ اللَّهُ لَهُ بِهِ طَرِيقًا إِلَى الْجَنَّةِ', en: 'Whoever travels a path seeking knowledge, Allah makes easy for him a path to Paradise.', fr: 'Quiconque emprunte un chemin à la recherche du savoir, Allah lui facilite un chemin vers le Paradis.', ref: 'Muslim 2699' },
  { ar: 'تَبَسُّمُكَ فِي وَجْهِ أَخِيكَ لَكَ صَدَقَةٌ', en: 'Your smile in the face of your brother is charity.', fr: 'Ton sourire au visage de ton frère est une aumône.', ref: 'Tirmidhi 1956 (hasan)' },
  { ar: 'إِنَّ اللَّهَ يُحِبُّ إِذَا عَمِلَ أَحَدُكُمْ عَمَلًا أَنْ يُتْقِنَهُ', en: 'Allah loves that when one of you does a job, he does it well.', fr: 'Allah aime que, lorsque l’un de vous fait un travail, il le fasse avec soin.', ref: 'Bayhaqi, Shu‘ab al-Iman (hasan)' },
]
